apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: sshd
  name: sshd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sshd
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sshd
    spec:
      containers:
      - image: mercisi/ubuntu18-supervisord:sshd
        imagePullPolicy: IfNotPresent
        name: ubuntu18-supervisord
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
          - containerPort: 22
        # envFrom:
        # - configMapRef:
        #     name: sshd-envs
        envFrom:
        - configMapRef:
            name: sshd-envs

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
