apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: couchdb
  name: couchdb
  # namespace: {{ .Values.namespaceToInstall }}
spec:
  # clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - name: default
    port: 5984
    protocol: TCP
    targetPort: 5984
  - port: 5986
    name: administrative
    protocol: TCP
    targetPort: 5986
  selector:
    app: couchdb
  # type: NodePort

