apiVersion: v1
kind: PersistentVolume
metadata:
  name: couchdb-clients-app-data
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/app-data"
