apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-clients-app-data-claim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi