apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: couchdb-server
  name: couchdb-server
  # namespace: {{ .Values.namespaceToInstall }}
spec:
  ports:
  - name: default
    port: 5984
    protocol: TCP
    targetPort: 5984
  - port: 5986
    name: administrative
    protocol: TCP
    targetPort: 5986
  selector:
    app: couchdb-server
  type: NodePort

